#!/usr/bin/env python3
from os.path import dirname, abspath, join
import sys

THIS_DIR = dirname(__file__)
REPO_DIR = abspath(join(THIS_DIR, '..'))
sys.path.insert(0, REPO_DIR)
import helpers.writeLastCommitToFile.writeLastCommitToFile as lastCommitWriter


logFilePath = REPO_DIR + "/showcase/performanceTests/shortGenerationPerformance_EachCommit.txt"
lastCommitWriter.lastCommitToFile(logFilePath)
